// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anonymous_sessions.sql

package sqlcdb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAnonymousAllocations = `-- name: ClaimAnonymousAllocations :many
WITH promoted AS (
    UPDATE disk_allocations
       SET user_id    = $1::uuid,
           expires_at = NULL
     WHERE id IN (
         SELECT allocation_id FROM sessions_anonymous
          WHERE device_id = $2::text
            AND claimed_at IS NULL
            AND created_at > now() - INTERVAL '5 hours'
     )
     AND user_id IS NULL
    RETURNING id
)
UPDATE sessions_anonymous
   SET claimed_at = now(),
       claimed_by = $1::uuid
 WHERE device_id = $2::text
   AND claimed_at IS NULL
   AND allocation_id IN (SELECT id FROM promoted)
RETURNING allocation_id
`

type ClaimAnonymousAllocationsParams struct {
	UserID   pgtype.UUID
	DeviceID string
}

// Two-step: promote allocations, then mark sessions claimed.
func (q *Queries) ClaimAnonymousAllocations(ctx context.Context, arg ClaimAnonymousAllocationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, claimAnonymousAllocations, arg.UserID, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var allocation_id pgtype.UUID
		if err := rows.Scan(&allocation_id); err != nil {
			return nil, err
		}
		items = append(items, allocation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAnonymousSessionsForIP = `-- name: CountAnonymousSessionsForIP :one
SELECT count(*)::int AS n FROM sessions_anonymous
WHERE ip_address = $1 AND created_at > now() - INTERVAL '5 minutes'
`

func (q *Queries) CountAnonymousSessionsForIP(ctx context.Context, ipAddress netip.Addr) (int32, error) {
	row := q.db.QueryRow(ctx, countAnonymousSessionsForIP, ipAddress)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countUnclaimedAnonymousSessionsForDevice = `-- name: CountUnclaimedAnonymousSessionsForDevice :one
SELECT count(*)::int AS n FROM sessions_anonymous
WHERE device_id = $1
  AND claimed_at IS NULL
  AND created_at > now() - INTERVAL '5 hours'
`

func (q *Queries) CountUnclaimedAnonymousSessionsForDevice(ctx context.Context, deviceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnclaimedAnonymousSessionsForDevice, deviceID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteUnclaimedExpiredAnonymousAllocations = `-- name: DeleteUnclaimedExpiredAnonymousAllocations :many
DELETE FROM disk_allocations
 WHERE user_id IS NULL
   AND expires_at IS NOT NULL
   AND created_at < now() - INTERVAL '5 hours'
   AND id IN (
       SELECT allocation_id FROM sessions_anonymous
        WHERE claimed_at IS NULL
   )
RETURNING id
`

func (q *Queries) DeleteUnclaimedExpiredAnonymousAllocations(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteUnclaimedExpiredAnonymousAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnonymousSession = `-- name: GetAnonymousSession :one
SELECT session_id, allocation_id, device_id, cert_serial, spawner_url, ip_address, user_agent, created_at, claimed_at, claimed_by FROM sessions_anonymous WHERE session_id = $1
`

func (q *Queries) GetAnonymousSession(ctx context.Context, sessionID string) (AnonymousSession, error) {
	row := q.db.QueryRow(ctx, getAnonymousSession, sessionID)
	var i AnonymousSession
	err := row.Scan(
		&i.SessionID,
		&i.AllocationID,
		&i.DeviceID,
		&i.CertSerial,
		&i.SpawnerUrl,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
	)
	return i, err
}

const getAnonymousSessionAllocation = `-- name: GetAnonymousSessionAllocation :one
SELECT sa.session_id, sa.allocation_id, sa.device_id, sa.cert_serial, sa.spawner_url, sa.ip_address, sa.user_agent, sa.created_at, sa.claimed_at, sa.claimed_by, da.expires_at AS allocation_expires_at
FROM sessions_anonymous sa
JOIN disk_allocations da ON da.id = sa.allocation_id
WHERE sa.session_id = $1
`

type GetAnonymousSessionAllocationRow struct {
	SessionID           string
	AllocationID        pgtype.UUID
	DeviceID            string
	CertSerial          string
	SpawnerUrl          string
	IpAddress           netip.Addr
	UserAgent           string
	CreatedAt           pgtype.Timestamptz
	ClaimedAt           pgtype.Timestamptz
	ClaimedBy           pgtype.UUID
	AllocationExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetAnonymousSessionAllocation(ctx context.Context, sessionID string) (GetAnonymousSessionAllocationRow, error) {
	row := q.db.QueryRow(ctx, getAnonymousSessionAllocation, sessionID)
	var i GetAnonymousSessionAllocationRow
	err := row.Scan(
		&i.SessionID,
		&i.AllocationID,
		&i.DeviceID,
		&i.CertSerial,
		&i.SpawnerUrl,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.AllocationExpiresAt,
	)
	return i, err
}

const insertAnonymousAllocation = `-- name: InsertAnonymousAllocation :one
INSERT INTO disk_allocations (user_id, size_bytes, expires_at)
VALUES (NULL, $1, $2)
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id
`

type InsertAnonymousAllocationParams struct {
	SizeBytes int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertAnonymousAllocation(ctx context.Context, arg InsertAnonymousAllocationParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, insertAnonymousAllocation, arg.SizeBytes, arg.ExpiresAt)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
	)
	return i, err
}

const insertAnonymousSession = `-- name: InsertAnonymousSession :one
INSERT INTO sessions_anonymous (
    session_id, allocation_id, device_id, cert_serial,
    spawner_url, ip_address, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING session_id, allocation_id, device_id, cert_serial, spawner_url, ip_address, user_agent, created_at, claimed_at, claimed_by
`

type InsertAnonymousSessionParams struct {
	SessionID    string
	AllocationID pgtype.UUID
	DeviceID     string
	CertSerial   string
	SpawnerUrl   string
	IpAddress    netip.Addr
	UserAgent    string
}

func (q *Queries) InsertAnonymousSession(ctx context.Context, arg InsertAnonymousSessionParams) (AnonymousSession, error) {
	row := q.db.QueryRow(ctx, insertAnonymousSession,
		arg.SessionID,
		arg.AllocationID,
		arg.DeviceID,
		arg.CertSerial,
		arg.SpawnerUrl,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AnonymousSession
	err := row.Scan(
		&i.SessionID,
		&i.AllocationID,
		&i.DeviceID,
		&i.CertSerial,
		&i.SpawnerUrl,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
	)
	return i, err
}

const listExpiredAnonymousSessions = `-- name: ListExpiredAnonymousSessions :many
SELECT sa.session_id, sa.allocation_id, sa.device_id, sa.cert_serial, sa.spawner_url, sa.ip_address, sa.user_agent, sa.created_at, sa.claimed_at, sa.claimed_by
FROM sessions_anonymous sa
JOIN disk_allocations da ON da.id = sa.allocation_id
WHERE sa.claimed_at IS NULL
  AND da.expires_at IS NOT NULL
  AND da.expires_at < now()
`

func (q *Queries) ListExpiredAnonymousSessions(ctx context.Context) ([]AnonymousSession, error) {
	rows, err := q.db.Query(ctx, listExpiredAnonymousSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnonymousSession{}
	for rows.Next() {
		var i AnonymousSession
		if err := rows.Scan(
			&i.SessionID,
			&i.AllocationID,
			&i.DeviceID,
			&i.CertSerial,
			&i.SpawnerUrl,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnonymousAllocationDeleted = `-- name: MarkAnonymousAllocationDeleted :one
UPDATE disk_allocations
   SET expires_at = now()
 WHERE id = $1
   AND user_id IS NULL
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id
`

func (q *Queries) MarkAnonymousAllocationDeleted(ctx context.Context, id pgtype.UUID) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, markAnonymousAllocationDeleted, id)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
	)
	return i, err
}
