// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, created_at, expires_at
`

type CreateAPITokenParams struct {
	UserID    pgtype.UUID
	Name      string
	TokenHash string
	Prefix    string
	ExpiresAt pgtype.Timestamptz
}

type CreateAPITokenRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Prefix    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT
    t.id, t.user_id, t.name, t.prefix, t.created_at, t.last_used_at, t.revoked_at, t.expires_at,
    u.tenant_id      AS user_tenant_id,
    u.suspended_at   AS user_suspended_at,
    ten.suspended_at AS tenant_suspended_at
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN tenants ten ON ten.id = u.tenant_id
WHERE t.token_hash = $1
`

type GetAPITokenByHashRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Name              string
	Prefix            string
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	UserTenantID      string
	UserSuspendedAt   pgtype.Timestamptz
	TenantSuspendedAt pgtype.Timestamptz
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.UserTenantID,
		&i.UserSuspendedAt,
		&i.TenantSuspendedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT id, user_id, name, prefix, created_at, last_used_at, revoked_at
FROM api_tokens
WHERE id = $1
`

type GetAPITokenByIDRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	Prefix     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) GetAPITokenByID(ctx context.Context, id pgtype.UUID) (GetAPITokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i GetAPITokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, name, prefix, created_at, last_used_at
FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAPITokensByUserRow struct {
	ID         pgtype.UUID
	Name       string
	Prefix     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPITokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByUserRow{}
	for rows.Next() {
		var i ListAPITokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	return err
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, id)
	return err
}
