// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disk_allocations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireMountLease = `-- name: AcquireMountLease :one
UPDATE disk_allocations
   SET bound_agent_id   = $2,
       bound_at         = CASE WHEN bound_agent_id = $2 THEN bound_at ELSE now() END,
       lease_expires_at = now() + $3::interval,
       mount_lease_token_hash = $4::text
 WHERE id = $1
   AND revoked_at IS NULL
   AND ($5::boolean
        OR bound_agent_id IS NULL
        OR bound_agent_id = $2
        OR lease_expires_at IS NULL
        OR lease_expires_at <= now())
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type AcquireMountLeaseParams struct {
	ID             pgtype.UUID
	BoundAgentID   pgtype.UUID
	Ttl            pgtype.Interval
	LeaseTokenHash string
	Force          bool
}

// Claim the allocation for $2 and set a fresh mount lease. An allocation belongs to a
// single orlop agent, so any caller the handler authorized (owning user + agent-scoped
// cert) IS that agent; a one-shot pod re-mounts with a FRESH enrollment ($2 is an FK
// into agent_enrollments, so it changes every turn) and takes over freely once the
// prior lease is released or expired. What it may NOT do without force is take over a
// lease that is still LIVE for a different enrollment: that incumbent is refreshing and
// mid-write, so a silent takeover turns a caller bug (concurrent double-mount) into
// silent data loss (issue #93). force=true is the explicit crash-recovery / take-over
// assertion — the caller states the incumbent's host is gone, skipping the TTL wait.
// Mount exclusivity is otherwise enforced by the handler's ownership check + the
// data-plane agent cert, and the acquire handler fences any stale server-side session
// so the new mount's hex is accepted.
func (q *Queries) AcquireMountLease(ctx context.Context, arg AcquireMountLeaseParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, acquireMountLease,
		arg.ID,
		arg.BoundAgentID,
		arg.Ttl,
		arg.LeaseTokenHash,
		arg.Force,
	)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const bindAllocation = `-- name: BindAllocation :one
UPDATE disk_allocations
   SET bound_agent_id = $3,
       bound_at       = now()
 WHERE id = $1
   AND user_id = $2
   AND revoked_at IS NULL
   AND bound_agent_id IS NULL
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type BindAllocationParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	BoundAgentID pgtype.UUID
}

func (q *Queries) BindAllocation(ctx context.Context, arg BindAllocationParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, bindAllocation, arg.ID, arg.UserID, arg.BoundAgentID)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const countActiveAllocationsForUser = `-- name: CountActiveAllocationsForUser :one
SELECT count(*) FROM disk_allocations
WHERE user_id = $1 AND revoked_at IS NULL
`

// Live (non-revoked) allocations a user still has. The purge path uses this
// to decide between a per-agent subtree purge (other agents share the tenant
// dir) and a whole-tenant unregister (this was the last one).
func (q *Queries) CountActiveAllocationsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAllocationsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurgePendingAllocations = `-- name: CountPurgePendingAllocations :one
SELECT count(*) FROM disk_allocations
WHERE revoked_at IS NOT NULL AND purged_at IS NULL
`

// Count every revoked allocation that has not completed the durable purge
// transition. This intentionally mirrors the allocator invariant rather than
// the sweeper's current batch eligibility filters.
func (q *Queries) CountPurgePendingAllocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPurgePendingAllocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const forceReleaseMountLease = `-- name: ForceReleaseMountLease :one
UPDATE disk_allocations
   SET bound_agent_id   = NULL,
       bound_at         = NULL,
       lease_expires_at = NULL,
       mount_lease_token_hash = NULL
 WHERE id = $1
   AND user_id = $2
   AND revoked_at IS NULL
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type ForceReleaseMountLeaseParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ForceReleaseMountLease(ctx context.Context, arg ForceReleaseMountLeaseParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, forceReleaseMountLease, arg.ID, arg.UserID)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const getAllocation = `-- name: GetAllocation :one
SELECT id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash FROM disk_allocations WHERE id = $1
`

func (q *Queries) GetAllocation(ctx context.Context, id pgtype.UUID) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, getAllocation, id)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const getAllocationByAgent = `-- name: GetAllocationByAgent :one
SELECT id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash FROM disk_allocations
WHERE agent_id = $1 AND revoked_at IS NULL
`

// Resolve an agent's live (non-revoked) allocation. agent_id is the orlop
// agent id, a globally-unique UUID, so a lookup by agent_id alone resolves to
// at most one live row.
func (q *Queries) GetAllocationByAgent(ctx context.Context, agentID pgtype.Text) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, getAllocationByAgent, agentID)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :one
INSERT INTO disk_allocations (user_id, size_bytes)
VALUES ($1, $2)
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type InsertAllocationParams struct {
	UserID    pgtype.UUID
	SizeBytes int64
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, insertAllocation, arg.UserID, arg.SizeBytes)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const listAllocationsForUser = `-- name: ListAllocationsForUser :many
SELECT id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash FROM disk_allocations
WHERE user_id = $1 AND user_id IS NOT NULL AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAllocationsForUser(ctx context.Context, userID pgtype.UUID) ([]DiskAllocation, error) {
	rows, err := q.db.Query(ctx, listAllocationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiskAllocation{}
	for rows.Next() {
		var i DiskAllocation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.BoundAgentID,
			&i.BoundAt,
			&i.LeaseExpiresAt,
			&i.ExpiresAt,
			&i.AgentID,
			&i.PurgedAt,
			&i.TenantID,
			&i.MountLeaseTokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgePendingAllocations = `-- name: ListPurgePendingAllocations :many
SELECT
    da.id          AS allocation_id,
    da.user_id     AS user_id,
    da.agent_id    AS agent_id,
    da.size_bytes  AS size_bytes,
    COALESCE(da.tenant_id, u.tenant_id) AS tenant_id,
    sp.ops_addr    AS ops_addr
FROM disk_allocations da
JOIN users u         ON u.id = da.user_id
LEFT JOIN server_vms sv  ON sv.tenant_id = COALESCE(da.tenant_id, u.tenant_id)
LEFT JOIN server_pool sp ON sp.data_addr = sv.data_addr
WHERE da.revoked_at IS NOT NULL
  AND da.purged_at IS NULL
  AND da.agent_id IS NOT NULL
  AND da.user_id IS NOT NULL
ORDER BY da.revoked_at ASC
LIMIT $1
`

type ListPurgePendingAllocationsRow struct {
	AllocationID pgtype.UUID
	UserID       pgtype.UUID
	AgentID      pgtype.Text
	SizeBytes    int64
	TenantID     string
	OpsAddr      pgtype.Text
}

// The purge sweeper's work queue: revoked agent allocations whose backend
// data has not been erased yet. LEFT JOINs the placement chain — an unplaced
// tenant (never enrolled, ops_addr NULL) has no server-side data and is
// marked purged without a data-plane call.
func (q *Queries) ListPurgePendingAllocations(ctx context.Context, limit int32) ([]ListPurgePendingAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listPurgePendingAllocations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurgePendingAllocationsRow{}
	for rows.Next() {
		var i ListPurgePendingAllocationsRow
		if err := rows.Scan(
			&i.AllocationID,
			&i.UserID,
			&i.AgentID,
			&i.SizeBytes,
			&i.TenantID,
			&i.OpsAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllocationPurged = `-- name: MarkAllocationPurged :one
UPDATE disk_allocations
   SET purged_at = now()
 WHERE id = $1
   AND revoked_at IS NOT NULL
   AND purged_at IS NULL
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

// CAS-claim the purge of a revoked allocation: only one caller transitions
// purged_at from NULL, so exactly one releases the pool reservation. Fails
// (zero rows) when the allocation is not revoked yet or already purged.
func (q *Queries) MarkAllocationPurged(ctx context.Context, id pgtype.UUID) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, markAllocationPurged, id)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const reassignAgentAllocation = `-- name: ReassignAgentAllocation :exec
UPDATE disk_allocations SET user_id = $2
WHERE agent_id = $1 AND revoked_at IS NULL
`

type ReassignAgentAllocationParams struct {
	AgentID pgtype.Text
	UserID  pgtype.UUID
}

// Re-home an agent's live allocation to a new billing owner (the orlop side of
// merging an anon trial's agent into an existing account). Only user_id changes;
// tenant_id — the per-agent storage tenant — is untouched, so the data stays exactly
// where it is. No quota gate: a merge is allowed even if it pushes the new owner over
// their ceiling.
func (q *Queries) ReassignAgentAllocation(ctx context.Context, arg ReassignAgentAllocationParams) error {
	_, err := q.db.Exec(ctx, reassignAgentAllocation, arg.AgentID, arg.UserID)
	return err
}

const refreshMountLease = `-- name: RefreshMountLease :one
UPDATE disk_allocations
   SET bound_agent_id = $2,
       lease_expires_at = now() + $3::interval,
       mount_lease_token_hash = CASE
           WHEN $4::text <> ''
           THEN $4::text
           ELSE mount_lease_token_hash
       END
 WHERE id = $1
   AND revoked_at IS NULL
   AND lease_expires_at IS NOT NULL
   AND lease_expires_at > now()
   AND (($5::text <> ''
         AND mount_lease_token_hash = $5::text)
        OR ($5::text = ''
            AND mount_lease_token_hash IS NULL
            AND bound_agent_id = $2))
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type RefreshMountLeaseParams struct {
	ID                pgtype.UUID
	BoundAgentID      pgtype.UUID
	Ttl               pgtype.Interval
	NewLeaseTokenHash string
	LeaseTokenHash    string
}

// The token is the stable identity of one mount process. It survives leaf-cert
// renewal (which changes bound_agent_id) but a takeover replaces it, so a
// displaced process cannot refresh its way back in. Legacy clients omit the
// token and retain the enrollment-id guard during a rolling upgrade.
// Expiry remains a hard boundary (issue #95): after it, the holder must go
// through AcquireMountLease so renewal follows the same takeover rules as any
// other claimant. Matching bound_agent_id only proves that no takeover has
// committed yet; without the expiry guard, a stale refresh can win a race
// against a waiter and resurrect ownership after its promised deadline.
func (q *Queries) RefreshMountLease(ctx context.Context, arg RefreshMountLeaseParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, refreshMountLease,
		arg.ID,
		arg.BoundAgentID,
		arg.Ttl,
		arg.NewLeaseTokenHash,
		arg.LeaseTokenHash,
	)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const releaseMountLease = `-- name: ReleaseMountLease :one
UPDATE disk_allocations
   SET bound_agent_id   = NULL,
       bound_at         = NULL,
       lease_expires_at = NULL,
       mount_lease_token_hash = NULL
 WHERE id = $1
   AND (bound_agent_id IS NULL
        OR ($3::text <> ''
            AND mount_lease_token_hash = $3::text)
        OR ($3::text = ''
            AND mount_lease_token_hash IS NULL
            AND bound_agent_id = $2))
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type ReleaseMountLeaseParams struct {
	ID             pgtype.UUID
	BoundAgentID   pgtype.UUID
	LeaseTokenHash string
}

func (q *Queries) ReleaseMountLease(ctx context.Context, arg ReleaseMountLeaseParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, releaseMountLease, arg.ID, arg.BoundAgentID, arg.LeaseTokenHash)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const revokeAllocation = `-- name: RevokeAllocation :one
UPDATE disk_allocations
   SET revoked_at = COALESCE(revoked_at, now())
 WHERE id = $1
   AND user_id = $2
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type RevokeAllocationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeAllocation(ctx context.Context, arg RevokeAllocationParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, revokeAllocation, arg.ID, arg.UserID)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const updateAllocationSize = `-- name: UpdateAllocationSize :one
UPDATE disk_allocations
   SET size_bytes = $3
 WHERE id = $1
   AND user_id = $2
   AND revoked_at IS NULL
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type UpdateAllocationSizeParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SizeBytes int64
}

// Raise (or lower) an allocation's hard size cap in place, preserving its id so the
// control-plane's stored disk handle stays valid. Used by the entity disk PATCH path
// to flip an anonymous agent's 128 MiB disk to the expandable registered size.
func (q *Queries) UpdateAllocationSize(ctx context.Context, arg UpdateAllocationSizeParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, updateAllocationSize, arg.ID, arg.UserID, arg.SizeBytes)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}

const upsertAgentAllocation = `-- name: UpsertAgentAllocation :one
INSERT INTO disk_allocations (user_id, agent_id, tenant_id, size_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id) WHERE revoked_at IS NULL
DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, size_bytes, created_at, revoked_at, bound_agent_id, bound_at, lease_expires_at, expires_at, agent_id, purged_at, tenant_id, mount_lease_token_hash
`

type UpsertAgentAllocationParams struct {
	UserID    pgtype.UUID
	AgentID   pgtype.Text
	TenantID  pgtype.Text
	SizeBytes int64
}

// Idempotent per-agent provisioning. The partial unique index
// disk_allocations_agent_active_idx (agent_id) WHERE revoked_at IS NULL
// guarantees at most one live allocation per agent (orlop agent ids are
// globally unique), so the conflict target reuses that predicate — and it
// matches GetAllocationByAgent's lookup-by-agent_id. On conflict we touch
// user_id (a no-op update) purely so RETURNING yields the existing row. Returns
// the allocation whose id is the caller's handle.
func (q *Queries) UpsertAgentAllocation(ctx context.Context, arg UpsertAgentAllocationParams) (DiskAllocation, error) {
	row := q.db.QueryRow(ctx, upsertAgentAllocation,
		arg.UserID,
		arg.AgentID,
		arg.TenantID,
		arg.SizeBytes,
	)
	var i DiskAllocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.BoundAgentID,
		&i.BoundAt,
		&i.LeaseExpiresAt,
		&i.ExpiresAt,
		&i.AgentID,
		&i.PurgedAt,
		&i.TenantID,
		&i.MountLeaseTokenHash,
	)
	return i, err
}
