// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner_capacity_reservations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlacedAllocationsForUserOnServer = `-- name: CountPlacedAllocationsForUserOnServer :one
SELECT count(DISTINCT sv.tenant_id)
FROM disk_allocations da
JOIN users u ON u.id = da.user_id
JOIN server_vms sv ON sv.tenant_id = COALESCE(da.tenant_id, u.tenant_id)
WHERE da.user_id = $1
  AND da.purged_at IS NULL
  AND sv.data_addr = $2
`

type CountPlacedAllocationsForUserOnServerParams struct {
	UserID   pgtype.UUID
	DataAddr string
}

func (q *Queries) CountPlacedAllocationsForUserOnServer(ctx context.Context, arg CountPlacedAllocationsForUserOnServerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlacedAllocationsForUserOnServer, arg.UserID, arg.DataAddr)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOwnerCapacityReservation = `-- name: CreateOwnerCapacityReservation :exec
INSERT INTO owner_capacity_reservations (user_id, server_id, size_bytes)
VALUES ($1, $2, $3)
`

type CreateOwnerCapacityReservationParams struct {
	UserID    pgtype.UUID
	ServerID  pgtype.UUID
	SizeBytes int64
}

func (q *Queries) CreateOwnerCapacityReservation(ctx context.Context, arg CreateOwnerCapacityReservationParams) error {
	_, err := q.db.Exec(ctx, createOwnerCapacityReservation, arg.UserID, arg.ServerID, arg.SizeBytes)
	return err
}

const deleteOwnerCapacityReservation = `-- name: DeleteOwnerCapacityReservation :execrows
DELETE FROM owner_capacity_reservations
WHERE user_id = $1 AND server_id = $2
`

type DeleteOwnerCapacityReservationParams struct {
	UserID   pgtype.UUID
	ServerID pgtype.UUID
}

func (q *Queries) DeleteOwnerCapacityReservation(ctx context.Context, arg DeleteOwnerCapacityReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnerCapacityReservation, arg.UserID, arg.ServerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnerCapacityReservations = `-- name: ListOwnerCapacityReservations :many
SELECT r.user_id, r.server_id, r.size_bytes, sp.data_addr, sp.ops_addr
FROM owner_capacity_reservations r
JOIN server_pool sp ON sp.id = r.server_id
WHERE r.user_id = $1
ORDER BY r.created_at, r.server_id
`

type ListOwnerCapacityReservationsRow struct {
	UserID    pgtype.UUID
	ServerID  pgtype.UUID
	SizeBytes int64
	DataAddr  string
	OpsAddr   string
}

func (q *Queries) ListOwnerCapacityReservations(ctx context.Context, userID pgtype.UUID) ([]ListOwnerCapacityReservationsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerCapacityReservations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerCapacityReservationsRow{}
	for rows.Next() {
		var i ListOwnerCapacityReservationsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ServerID,
			&i.SizeBytes,
			&i.DataAddr,
			&i.OpsAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnerCapacityReservationSize = `-- name: UpdateOwnerCapacityReservationSize :exec
UPDATE owner_capacity_reservations
SET size_bytes = $3
WHERE user_id = $1 AND server_id = $2
`

type UpdateOwnerCapacityReservationSizeParams struct {
	UserID    pgtype.UUID
	ServerID  pgtype.UUID
	SizeBytes int64
}

func (q *Queries) UpdateOwnerCapacityReservationSize(ctx context.Context, arg UpdateOwnerCapacityReservationSizeParams) error {
	_, err := q.db.Exec(ctx, updateOwnerCapacityReservationSize, arg.UserID, arg.ServerID, arg.SizeBytes)
	return err
}
