// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// An authorized mount unconditionally takes over the lease (only a revoked/missing
	// allocation fails). An allocation belongs to a single orlop agent, so any caller the
	// handler authorized (owning user + agent-scoped cert) IS that agent; a one-shot pod
	// re-mounts with a FRESH enrollment ($2 is an FK into agent_enrollments, so it changes
	// every turn) and must be able to take over the prior pod's lease — including one a
	// crashed/forcibly-killed pod leaked, without waiting out the TTL. Mount exclusivity is
	// enforced by the handler's ownership check + the data-plane agent cert, and the acquire
	// handler fences any stale server-side session so the new mount's hex is accepted.
	AcquireMountLease(ctx context.Context, arg AcquireMountLeaseParams) (DiskAllocation, error)
	// Record a revoked cert serial (issue #5). Idempotent: a serial already on the
	// deny-list is left untouched (the first revocation's reason/expiry win).
	AddCertRevocation(ctx context.Context, arg AddCertRevocationParams) error
	BindAllocation(ctx context.Context, arg BindAllocationParams) (DiskAllocation, error)
	// Two-step: promote allocations, then mark sessions claimed.
	ClaimAnonymousAllocations(ctx context.Context, arg ClaimAnonymousAllocationsParams) ([]pgtype.UUID, error)
	// Atomically spend a single-use agent-enroll token (issue #6). Matches only an
	// un-consumed 'agent_enroll' row; a replay or a lost concurrent race matches
	// zero rows and returns pgx.ErrNoRows, which the caller treats as "already
	// spent" and rejects. The purpose filter keeps device/admin/api multi-use
	// sessions out — they are never consumed here even when presented on the
	// enroll route. The literal mirrors devauth.PurposeAgentEnroll.
	ConsumeAgentEnrollToken(ctx context.Context, tokenHash string) (pgtype.UUID, error)
	// Live (non-revoked) allocations a user still has. The purge path uses this
	// to decide between a per-agent subtree purge (other agents share the tenant
	// dir) and a whole-tenant unregister (this was the last one).
	CountActiveAllocationsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountAnonymousSessionsForIP(ctx context.Context, ipAddress netip.Addr) (int32, error)
	CountUnclaimedAnonymousSessionsForDevice(ctx context.Context, deviceID string) (int32, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateAgentEnrollment(ctx context.Context, arg CreateAgentEnrollmentParams) (AgentEnrollment, error)
	CreateServerVM(ctx context.Context, arg CreateServerVMParams) (ServerVm, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Housekeeping: drop rows whose certs have already expired.
	DeleteExpiredCertRevocations(ctx context.Context) error
	// Remove a tenant's placement after its data-plane tenant was unregistered
	// (last-allocation purge). The next enroll for this tenant re-Reserves a
	// placement from the pool.
	DeleteServerVM(ctx context.Context, tenantID string) (int64, error)
	DeleteUnclaimedExpiredAnonymousAllocations(ctx context.Context) ([]pgtype.UUID, error)
	// Idempotent: create the tenant if it does not already exist. The caller
	// follows up with GetTenant when it needs the row. Used by /v1/entities
	// provisioning to lazily ensure the customer's per-user tenant.
	EnsureTenant(ctx context.Context, arg EnsureTenantParams) error
	// Idempotent: create the user with an explicit id (the orlop user UUID is
	// reused as the dg user id) if it does not already exist. Used by /v1/entities
	// provisioning so the disk allocation can reference the agent's owner.
	EnsureUserWithID(ctx context.Context, arg EnsureUserWithIDParams) error
	ForceReleaseMountLease(ctx context.Context, arg ForceReleaseMountLeaseParams) (DiskAllocation, error)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error)
	GetAPITokenByID(ctx context.Context, id pgtype.UUID) (GetAPITokenByIDRow, error)
	GetAccessTokenByHash(ctx context.Context, tokenHash string) (GetAccessTokenByHashRow, error)
	GetActiveEnrollmentByFingerprint(ctx context.Context, lower string) (AgentEnrollment, error)
	// Resolve a single enrollment by its id (a disk_allocations.bound_agent_id FK),
	// used to revoke the bound leaf's serial on lease release (issue #5).
	GetAgentEnrollment(ctx context.Context, id pgtype.UUID) (AgentEnrollment, error)
	GetAllocation(ctx context.Context, id pgtype.UUID) (DiskAllocation, error)
	// Resolve an agent's live (non-revoked) allocation. agent_id is the orlop
	// agent id, a globally-unique UUID, so a lookup by agent_id alone resolves to
	// at most one live row.
	GetAllocationByAgent(ctx context.Context, agentID pgtype.Text) (DiskAllocation, error)
	GetAnonymousSession(ctx context.Context, sessionID string) (AnonymousSession, error)
	GetAnonymousSessionAllocation(ctx context.Context, sessionID string) (GetAnonymousSessionAllocationRow, error)
	GetServerPoolByDataAddr(ctx context.Context, dataAddr string) (ServerPool, error)
	GetServerVMByTenant(ctx context.Context, tenantID string) (ServerVm, error)
	GetTenant(ctx context.Context, id string) (Tenant, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserForUpdate(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAllocation(ctx context.Context, arg InsertAllocationParams) (DiskAllocation, error)
	InsertAnonymousAllocation(ctx context.Context, arg InsertAnonymousAllocationParams) (DiskAllocation, error)
	InsertAnonymousSession(ctx context.Context, arg InsertAnonymousSessionParams) (AnonymousSession, error)
	ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPITokensByUserRow, error)
	// The deny-list the reconcile loop pushes to data-plane servers: serials whose
	// certs have not yet expired (an expired cert fails verification anyway).
	ListActiveCertRevocations(ctx context.Context) ([]ListActiveCertRevocationsRow, error)
	ListActiveEnrollmentsForUser(ctx context.Context, userID pgtype.UUID) ([]AgentEnrollment, error)
	// Distinct orlop-server ops addresses that currently host at least one placed
	// tenant — the push targets for the deny-list reconcile.
	ListActiveServerOpsAddrs(ctx context.Context) ([]string, error)
	ListAllocationsForUser(ctx context.Context, userID pgtype.UUID) ([]DiskAllocation, error)
	ListExpiredAnonymousSessions(ctx context.Context) ([]AnonymousSession, error)
	// Active, placed, registered allocations that still have room to grow toward
	// their promised ceiling (users.quota_bytes). The storage autoscaler polls this
	// to decide which tenants to expand. Anonymous allocations (user_id IS NULL) are
	// excluded — they bypass server_pool and are ephemeral.
	ListGrowableAllocations(ctx context.Context) ([]ListGrowableAllocationsRow, error)
	// The purge sweeper's work queue: revoked agent allocations whose backend
	// data has not been erased yet. LEFT JOINs the placement chain — an unplaced
	// tenant (never enrolled, ops_addr NULL) has no server-side data and is
	// marked purged without a data-plane call.
	ListPurgePendingAllocations(ctx context.Context, limit int32) ([]ListPurgePendingAllocationsRow, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	// CAS-claim the purge of a revoked allocation: only one caller transitions
	// purged_at from NULL, so exactly one releases the pool reservation. Fails
	// (zero rows) when the allocation is not revoked yet or already purged.
	MarkAllocationPurged(ctx context.Context, id pgtype.UUID) (DiskAllocation, error)
	MarkAnonymousAllocationDeleted(ctx context.Context, id pgtype.UUID) (DiskAllocation, error)
	MarkServerVMProvisioned(ctx context.Context, arg MarkServerVMProvisionedParams) (ServerVm, error)
	PickBestAvailableServer(ctx context.Context, freeBytes int64) (ServerPool, error)
	// Re-home an agent's live allocation to a new billing owner (the orlop side of
	// merging an anon trial's agent into an existing account). Only user_id changes;
	// tenant_id — the per-agent storage tenant — is untouched, so the data stays exactly
	// where it is. No quota gate: a merge is allowed even if it pushes the new owner over
	// their ceiling.
	ReassignAgentAllocation(ctx context.Context, arg ReassignAgentAllocationParams) error
	// Flip servers between 'available' and 'draining' based on a growth-headroom
	// buffer: a server with less than buffer_fraction of its capacity free is
	// 'draining' (no new placements, residents may still grow); one at/above the
	// buffer returns to 'available'. Operator-set 'unavailable' servers are left
	// untouched.
	ReconcileServerStatus(ctx context.Context, bufferFraction float64) error
	RefreshMountLease(ctx context.Context, arg RefreshMountLeaseParams) (DiskAllocation, error)
	ReleaseCapacity(ctx context.Context, arg ReleaseCapacityParams) (ServerPool, error)
	ReleaseMountLease(ctx context.Context, arg ReleaseMountLeaseParams) (DiskAllocation, error)
	ReserveCapacity(ctx context.Context, arg ReserveCapacityParams) (ServerPool, error)
	// Like ReserveCapacity, but also permits a 'draining' server. A draining server
	// takes no NEW tenants (PickBestAvailableServer filters status='available'), yet
	// an existing resident must still be able to grow in place — otherwise elastic
	// growth would stall the moment a server crossed its high-water mark.
	ReserveCapacityForGrowth(ctx context.Context, arg ReserveCapacityForGrowthParams) (ServerPool, error)
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error
	RevokeAccessToken(ctx context.Context, tokenHash string) error
	RevokeAllocation(ctx context.Context, arg RevokeAllocationParams) (DiskAllocation, error)
	// Sets a user's aggregate quota. Used to provision the shared control-plane system
	// user with a high ceiling so per-agent caps are governed by each allocation's size.
	SetUserQuota(ctx context.Context, arg SetUserQuotaParams) error
	SumActiveAllocationBytes(ctx context.Context, userID pgtype.UUID) (int64, error)
	SuspendTenant(ctx context.Context, id string) error
	SuspendUser(ctx context.Context, id pgtype.UUID) error
	TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error
	UnsuspendUser(ctx context.Context, id pgtype.UUID) error
	// Raise (or lower) an allocation's hard size cap in place, preserving its id so the
	// control-plane's stored disk handle stays valid. Used by the entity disk PATCH path
	// to flip an anonymous agent's 128 MiB disk to the expandable registered size.
	UpdateAllocationSize(ctx context.Context, arg UpdateAllocationSizeParams) (DiskAllocation, error)
	// Idempotent per-agent provisioning. The partial unique index
	// disk_allocations_agent_active_idx (agent_id) WHERE revoked_at IS NULL
	// guarantees at most one live allocation per agent (orlop agent ids are
	// globally unique), so the conflict target reuses that predicate — and it
	// matches GetAllocationByAgent's lookup-by-agent_id. On conflict we touch
	// user_id (a no-op update) purely so RETURNING yields the existing row. Returns
	// the allocation whose id is the caller's handle.
	UpsertAgentAllocation(ctx context.Context, arg UpsertAgentAllocationParams) (DiskAllocation, error)
	UpsertServerPool(ctx context.Context, arg UpsertServerPoolParams) (ServerPool, error)
}

var _ Querier = (*Queries)(nil)
