// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Claim the allocation for $2 and set a fresh mount lease. An allocation belongs to a
	// single orlop agent, so any caller the handler authorized (owning user + agent-scoped
	// cert) IS that agent; a one-shot pod re-mounts with a FRESH enrollment ($2 is an FK
	// into agent_enrollments, so it changes every turn) and takes over freely once the
	// prior lease is released or expired. What it may NOT do without force is take over a
	// lease that is still LIVE for a different enrollment: that incumbent is refreshing and
	// mid-write, so a silent takeover turns a caller bug (concurrent double-mount) into
	// silent data loss (issue #93). force=true is the explicit crash-recovery / take-over
	// assertion — the caller states the incumbent's host is gone, skipping the TTL wait.
	// Mount exclusivity is otherwise enforced by the handler's ownership check + the
	// data-plane agent cert, and the acquire handler fences any stale server-side session
	// so the new mount's hex is accepted.
	AcquireMountLease(ctx context.Context, arg AcquireMountLeaseParams) (DiskAllocation, error)
	// Record a revoked cert serial (issue #5). Idempotent: a serial already on the
	// deny-list is left untouched (the first revocation's reason/expiry win).
	AddCertRevocation(ctx context.Context, arg AddCertRevocationParams) error
	BindAllocation(ctx context.Context, arg BindAllocationParams) (DiskAllocation, error)
	// Atomically spend a single-use agent-enroll token (issue #6). Matches only an
	// un-consumed 'agent_enroll' row; a replay or a lost concurrent race matches
	// zero rows and returns pgx.ErrNoRows, which the caller treats as "already
	// spent" and rejects. The purpose filter keeps device/admin/api multi-use
	// sessions out — they are never consumed here even when presented on the
	// enroll route. The literal mirrors devauth.PurposeAgentEnroll.
	ConsumeAgentEnrollToken(ctx context.Context, tokenHash string) (pgtype.UUID, error)
	// Live (non-revoked) allocations a user still has. The purge path uses this
	// to decide between a per-agent subtree purge (other agents share the tenant
	// dir) and a whole-tenant unregister (this was the last one).
	CountActiveAllocationsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountPlacedAllocationsForUserOnServer(ctx context.Context, arg CountPlacedAllocationsForUserOnServerParams) (int64, error)
	// Count every revoked allocation that has not completed the durable purge
	// transition. This intentionally mirrors the allocator invariant rather than
	// the sweeper's current batch eligibility filters.
	CountPurgePendingAllocations(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateAgentEnrollment(ctx context.Context, arg CreateAgentEnrollmentParams) (AgentEnrollment, error)
	CreateOwnerCapacityReservation(ctx context.Context, arg CreateOwnerCapacityReservationParams) error
	CreateServerVM(ctx context.Context, arg CreateServerVMParams) (ServerVm, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOwnerCapacityReservation(ctx context.Context, arg DeleteOwnerCapacityReservationParams) (int64, error)
	// Remove a tenant's placement after its data-plane tenant was unregistered
	// (last-allocation purge). The next enroll for this tenant re-Reserves a
	// placement from the pool.
	DeleteServerVM(ctx context.Context, tenantID string) (int64, error)
	// Idempotent: create the tenant if it does not already exist. The caller
	// follows up with GetTenant when it needs the row. Used by /v1/entities
	// provisioning to lazily ensure the customer's per-user tenant.
	EnsureTenant(ctx context.Context, arg EnsureTenantParams) error
	// Idempotent: create the user with an explicit id (the orlop user UUID is
	// reused as the dg user id) if it does not already exist. Used by /v1/entities
	// provisioning so the disk allocation can reference the agent's owner.
	EnsureUserWithID(ctx context.Context, arg EnsureUserWithIDParams) error
	ForceReleaseMountLease(ctx context.Context, arg ForceReleaseMountLeaseParams) (DiskAllocation, error)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error)
	GetAPITokenByID(ctx context.Context, id pgtype.UUID) (GetAPITokenByIDRow, error)
	GetAccessTokenByHash(ctx context.Context, tokenHash string) (GetAccessTokenByHashRow, error)
	GetActiveEnrollmentByFingerprint(ctx context.Context, lower string) (AgentEnrollment, error)
	// Resolve a single enrollment by its id (a disk_allocations.bound_agent_id FK),
	// used to revoke the bound leaf's serial on lease release (issue #5).
	GetAgentEnrollment(ctx context.Context, id pgtype.UUID) (AgentEnrollment, error)
	GetAllocation(ctx context.Context, id pgtype.UUID) (DiskAllocation, error)
	// Resolve an agent's live (non-revoked) allocation. agent_id is the orlop
	// agent id, a globally-unique UUID, so a lookup by agent_id alone resolves to
	// at most one live row.
	GetAllocationByAgent(ctx context.Context, agentID pgtype.Text) (DiskAllocation, error)
	GetServerPoolByDataAddr(ctx context.Context, dataAddr string) (ServerPool, error)
	GetServerVMByTenant(ctx context.Context, tenantID string) (ServerVm, error)
	GetTenant(ctx context.Context, id string) (Tenant, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserForUpdate(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAllocation(ctx context.Context, arg InsertAllocationParams) (DiskAllocation, error)
	ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPITokensByUserRow, error)
	// The deny-list the reconcile loop pushes to data-plane servers: serials whose
	// certs have not yet expired (an expired cert fails verification anyway).
	ListActiveCertRevocations(ctx context.Context) ([]ListActiveCertRevocationsRow, error)
	ListActiveEnrollmentsForUser(ctx context.Context, userID pgtype.UUID) ([]AgentEnrollment, error)
	// Distinct orlop-server ops addresses that currently host at least one placed
	// tenant — the push targets for the deny-list reconcile.
	ListActiveServerOpsAddrs(ctx context.Context) ([]string, error)
	ListAllocationsForUser(ctx context.Context, userID pgtype.UUID) ([]DiskAllocation, error)
	ListOwnerCapacityReservations(ctx context.Context, userID pgtype.UUID) ([]ListOwnerCapacityReservationsRow, error)
	// The purge sweeper's work queue: revoked agent allocations whose backend
	// data has not been erased yet. LEFT JOINs the placement chain — an unplaced
	// tenant (never enrolled, ops_addr NULL) has no server-side data and is
	// marked purged without a data-plane call.
	ListPurgePendingAllocations(ctx context.Context, limit int32) ([]ListPurgePendingAllocationsRow, error)
	// Small projection used by the Prometheus collector. Keep the stable database
	// id as the only label; addresses and status may change and would create stale
	// time series.
	ListServerPoolCapacity(ctx context.Context) ([]ListServerPoolCapacityRow, error)
	// CAS-claim the purge of a revoked allocation: only one caller transitions
	// purged_at from NULL, so exactly one releases the pool reservation. Fails
	// (zero rows) when the allocation is not revoked yet or already purged.
	MarkAllocationPurged(ctx context.Context, id pgtype.UUID) (DiskAllocation, error)
	PickBestAvailableServer(ctx context.Context, freeBytes int64) (ServerPool, error)
	// Re-home an agent's live allocation to a new billing owner (the orlop side of
	// merging an anon trial's agent into an existing account). Only user_id changes;
	// tenant_id — the per-agent storage tenant — is untouched, so the data stays exactly
	// where it is. No quota gate: a merge is allowed even if it pushes the new owner over
	// their ceiling.
	ReassignAgentAllocation(ctx context.Context, arg ReassignAgentAllocationParams) error
	// Flip servers between 'available' and 'draining' based on a growth-headroom
	// buffer: a server with less than buffer_fraction of its capacity free is
	// 'draining' (no new placements, residents may still grow); one at/above the
	// buffer returns to 'available'. Operator-set 'unavailable' servers are left
	// untouched.
	ReconcileServerStatus(ctx context.Context, bufferFraction float64) error
	// Expiry remains a hard boundary (issue #95): after it, the holder must go
	// through AcquireMountLease so renewal follows the same takeover rules as any
	// other claimant. Matching bound_agent_id only proves that no takeover has
	// committed yet; without the expiry guard, a stale refresh can win a race
	// against a waiter and resurrect ownership after its promised deadline.
	RefreshMountLease(ctx context.Context, arg RefreshMountLeaseParams) (DiskAllocation, error)
	ReleaseCapacity(ctx context.Context, arg ReleaseCapacityParams) (ServerPool, error)
	ReleaseMountLease(ctx context.Context, arg ReleaseMountLeaseParams) (DiskAllocation, error)
	ReserveCapacity(ctx context.Context, arg ReserveCapacityParams) (ServerPool, error)
	// Like ReserveCapacity, but also permits a 'draining' server. A draining server
	// takes no NEW tenants (PickBestAvailableServer filters status='available'), yet
	// an existing resident must still be able to grow in place — otherwise elastic
	// growth would stall the moment a server crossed its high-water mark.
	ReserveCapacityForGrowth(ctx context.Context, arg ReserveCapacityForGrowthParams) (ServerPool, error)
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error
	RevokeAllocation(ctx context.Context, arg RevokeAllocationParams) (DiskAllocation, error)
	SumActiveAllocationBytes(ctx context.Context, userID pgtype.UUID) (int64, error)
	SuspendTenant(ctx context.Context, id string) error
	SuspendUser(ctx context.Context, id pgtype.UUID) error
	TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error
	// Raise (or lower) an allocation's hard size cap in place, preserving its id so the
	// control-plane's stored disk handle stays valid. Used by the entity disk PATCH path
	// to flip an anonymous agent's 128 MiB disk to the expandable registered size.
	UpdateAllocationSize(ctx context.Context, arg UpdateAllocationSizeParams) (DiskAllocation, error)
	UpdateOwnerCapacityReservationSize(ctx context.Context, arg UpdateOwnerCapacityReservationSizeParams) error
	// Idempotent per-agent provisioning. The partial unique index
	// disk_allocations_agent_active_idx (agent_id) WHERE revoked_at IS NULL
	// guarantees at most one live allocation per agent (orlop agent ids are
	// globally unique), so the conflict target reuses that predicate — and it
	// matches GetAllocationByAgent's lookup-by-agent_id. On conflict we touch
	// user_id (a no-op update) purely so RETURNING yields the existing row. Returns
	// the allocation whose id is the caller's handle.
	UpsertAgentAllocation(ctx context.Context, arg UpsertAgentAllocationParams) (DiskAllocation, error)
	UpsertServerPool(ctx context.Context, arg UpsertServerPoolParams) (ServerPool, error)
}

var _ Querier = (*Queries)(nil)
