// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_pool.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getServerPoolByDataAddr = `-- name: GetServerPoolByDataAddr :one
SELECT id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at FROM server_pool WHERE data_addr = $1
`

func (q *Queries) GetServerPoolByDataAddr(ctx context.Context, dataAddr string) (ServerPool, error) {
	row := q.db.QueryRow(ctx, getServerPoolByDataAddr, dataAddr)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pickBestAvailableServer = `-- name: PickBestAvailableServer :one
SELECT id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at FROM server_pool
WHERE status = 'available' AND free_bytes >= $1
ORDER BY free_bytes DESC, data_addr
LIMIT 1
`

func (q *Queries) PickBestAvailableServer(ctx context.Context, freeBytes int64) (ServerPool, error) {
	row := q.db.QueryRow(ctx, pickBestAvailableServer, freeBytes)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reconcileServerStatus = `-- name: ReconcileServerStatus :exec
UPDATE server_pool
SET status = CASE
        WHEN free_bytes::float8 < total_bytes::float8 * $1::float8
        THEN 'draining' ELSE 'available' END,
    updated_at = now()
WHERE status IN ('available', 'draining')
`

// Flip servers between 'available' and 'draining' based on a growth-headroom
// buffer: a server with less than buffer_fraction of its capacity free is
// 'draining' (no new placements, residents may still grow); one at/above the
// buffer returns to 'available'. Operator-set 'unavailable' servers are left
// untouched.
func (q *Queries) ReconcileServerStatus(ctx context.Context, bufferFraction float64) error {
	_, err := q.db.Exec(ctx, reconcileServerStatus, bufferFraction)
	return err
}

const releaseCapacity = `-- name: ReleaseCapacity :one
UPDATE server_pool
SET free_bytes = LEAST(free_bytes + $1, total_bytes),
    updated_at = now()
WHERE id = $2
RETURNING id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at
`

type ReleaseCapacityParams struct {
	FreeBytes int64
	ID        pgtype.UUID
}

func (q *Queries) ReleaseCapacity(ctx context.Context, arg ReleaseCapacityParams) (ServerPool, error) {
	row := q.db.QueryRow(ctx, releaseCapacity, arg.FreeBytes, arg.ID)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveCapacity = `-- name: ReserveCapacity :one
UPDATE server_pool
SET free_bytes = free_bytes - $1,
    updated_at = now()
WHERE id = $2
  AND status = 'available'
  AND free_bytes >= $1
RETURNING id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at
`

type ReserveCapacityParams struct {
	FreeBytes int64
	ID        pgtype.UUID
}

func (q *Queries) ReserveCapacity(ctx context.Context, arg ReserveCapacityParams) (ServerPool, error) {
	row := q.db.QueryRow(ctx, reserveCapacity, arg.FreeBytes, arg.ID)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveCapacityForGrowth = `-- name: ReserveCapacityForGrowth :one
UPDATE server_pool
SET free_bytes = free_bytes - $1,
    updated_at = now()
WHERE id = $2
  AND status IN ('available', 'draining')
  AND free_bytes >= $1
RETURNING id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at
`

type ReserveCapacityForGrowthParams struct {
	FreeBytes int64
	ID        pgtype.UUID
}

// Like ReserveCapacity, but also permits a 'draining' server. A draining server
// takes no NEW tenants (PickBestAvailableServer filters status='available'), yet
// an existing resident must still be able to grow in place — otherwise elastic
// growth would stall the moment a server crossed its high-water mark.
func (q *Queries) ReserveCapacityForGrowth(ctx context.Context, arg ReserveCapacityForGrowthParams) (ServerPool, error) {
	row := q.db.QueryRow(ctx, reserveCapacityForGrowth, arg.FreeBytes, arg.ID)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServerPool = `-- name: UpsertServerPool :one
INSERT INTO server_pool (data_addr, ops_addr, total_bytes, free_bytes, status)
VALUES ($1, $2, $3, $4, COALESCE(NULLIF($5::text, ''), 'available'))
ON CONFLICT (data_addr) DO UPDATE SET
    ops_addr = EXCLUDED.ops_addr,
    total_bytes = EXCLUDED.total_bytes,
    free_bytes = EXCLUDED.free_bytes,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, data_addr, ops_addr, total_bytes, free_bytes, status, created_at, updated_at
`

type UpsertServerPoolParams struct {
	DataAddr   string
	OpsAddr    string
	TotalBytes int64
	FreeBytes  int64
	Status     string
}

func (q *Queries) UpsertServerPool(ctx context.Context, arg UpsertServerPoolParams) (ServerPool, error) {
	row := q.db.QueryRow(ctx, upsertServerPool,
		arg.DataAddr,
		arg.OpsAddr,
		arg.TotalBytes,
		arg.FreeBytes,
		arg.Status,
	)
	var i ServerPool
	err := row.Scan(
		&i.ID,
		&i.DataAddr,
		&i.OpsAddr,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
