// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcdb

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name)
VALUES ($1, $2)
RETURNING id, name, suspended_at, created_at
`

type CreateTenantParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SuspendedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ensureTenant = `-- name: EnsureTenant :exec
INSERT INTO tenants (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type EnsureTenantParams struct {
	ID   string
	Name string
}

// Idempotent: create the tenant if it does not already exist. The caller
// follows up with GetTenant when it needs the row. Used by /v1/entities
// provisioning to lazily ensure the customer's per-user tenant.
func (q *Queries) EnsureTenant(ctx context.Context, arg EnsureTenantParams) error {
	_, err := q.db.Exec(ctx, ensureTenant, arg.ID, arg.Name)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, suspended_at, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SuspendedAt,
		&i.CreatedAt,
	)
	return i, err
}

const suspendTenant = `-- name: SuspendTenant :exec
UPDATE tenants SET suspended_at = now() WHERE id = $1
`

func (q *Queries) SuspendTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, suspendTenant, id)
	return err
}
