// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, tenant_id)
VALUES ($1, $2)
RETURNING id, email, tenant_id, role, suspended_at, quota_bytes, created_at
`

type CreateUserParams struct {
	Email    string
	TenantID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.SuspendedAt,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const ensureUserWithID = `-- name: EnsureUserWithID :exec
INSERT INTO users (id, tenant_id, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type EnsureUserWithIDParams struct {
	ID       pgtype.UUID
	TenantID string
	Email    string
}

// Idempotent: create the user with an explicit id (the orlop user UUID is
// reused as the dg user id) if it does not already exist. Used by /v1/entities
// provisioning so the disk allocation can reference the agent's owner.
func (q *Queries) EnsureUserWithID(ctx context.Context, arg EnsureUserWithIDParams) error {
	_, err := q.db.Exec(ctx, ensureUserWithID, arg.ID, arg.TenantID, arg.Email)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, tenant_id, role, suspended_at, quota_bytes, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.SuspendedAt,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, tenant_id, role, suspended_at, quota_bytes, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.SuspendedAt,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, email, tenant_id, role, suspended_at, quota_bytes, created_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.SuspendedAt,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const sumActiveAllocationBytes = `-- name: SumActiveAllocationBytes :one
SELECT COALESCE(SUM(size_bytes), 0)::BIGINT AS total_bytes
FROM disk_allocations
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) SumActiveAllocationBytes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveAllocationBytes, userID)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users SET suspended_at = now() WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}
