//! Persistent on-disk chunk cache for the data plane.
//!
//! Chunks live at `<root>/chunks/<hh>/<blake3-hex>`; an `index.sqlite`
//! sibling tracks `(hash, size, last_access)` for LRU eviction.
//! `ChunkCache::get` hash-verifies on every hit; mismatches are deleted,
//! audited (`cache_corrupt`), and reported as a miss so the caller refetches.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{Context, Result};
use parking_lot::Mutex;
use rusqlite::{params, Connection, OptionalExtension};

use crate::audit::AuditLog;

const SCHEMA: &str = r#"
CREATE TABLE IF NOT EXISTS chunks (
    hash BLOB PRIMARY KEY,
    size INTEGER NOT NULL,
    last_access INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS chunks_last_access ON chunks(last_access);
"#;

#[derive(Debug, Clone, Copy)]
pub struct CacheStats {
    pub count: u64,
    pub total_bytes: u64,
    pub max_bytes: u64,
}

/// Result of `prune_dry_run`: the LRU-ordered list of `(hash, size)` pairs
/// that *would* be evicted to bring total usage under low-water, without
/// mutating any state on disk or in the index.
pub struct DryRunPlan {
    pub would_evict: Vec<(Vec<u8>, u64)>,
    pub bytes_freed: u64,
}

pub struct ChunkCache {
    root: PathBuf,
    db: Mutex<Connection>,
    max_bytes: u64,
    audit: Option<AuditLog>,
}

impl ChunkCache {
    pub fn open(root: PathBuf, max_bytes: u64, audit: Option<AuditLog>) -> Result<Arc<Self>> {
        std::fs::create_dir_all(root.join("chunks")).context("create chunk cache root")?;
        let db_path = root.join("index.sqlite");
        let db =
            Connection::open(&db_path).with_context(|| format!("open {}", db_path.display()))?;
        // WAL + synchronous=NORMAL keeps the hot path off fsync-per-write.
        // Index rows can be regenerated by re-fetching chunks, so we don't
        // need synchronous=FULL durability — losing the last few last_access
        // updates on power loss is fine.
        db.execute_batch(
            "PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL; PRAGMA temp_store = MEMORY;",
        )
        .context("apply chunk cache pragmas")?;
        db.execute_batch(SCHEMA)
            .context("apply chunk cache schema")?;
        Ok(Arc::new(Self {
            root,
            db: Mutex::new(db),
            max_bytes,
            audit,
        }))
    }

    /// Default root for the persistent chunk cache:
    /// `$XDG_CACHE_HOME/orlop`, or `$HOME/.cache/orlop`. Returns `None` if
    /// neither env var is set.
    pub fn default_root() -> Option<PathBuf> {
        std::env::var_os("XDG_CACHE_HOME")
            .map(PathBuf::from)
            .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))
            .map(|base| base.join("orlop"))
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    fn chunk_path(&self, hash: &[u8]) -> PathBuf {
        let hex = hex_encode(hash);
        self.root.join("chunks").join(&hex[..2]).join(&hex)
    }

    pub fn put(&self, hash: &[u8], bytes: &[u8]) -> Result<()> {
        if hash.len() != 32 {
            anyhow::bail!("chunk hash must be 32 bytes, got {}", hash.len());
        }
        let path = self.chunk_path(hash);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).context("create chunk shard dir")?;
        }

        // Atomic write: temp file in the same dir + rename. Killing the
        // process mid-write leaves at most a `.tmp` orphan, never a partial
        // chunk under its real hash filename.
        let tmp = path.with_extension("tmp");
        std::fs::write(&tmp, bytes).with_context(|| format!("write {}", tmp.display()))?;
        std::fs::rename(&tmp, &path).with_context(|| format!("rename {}", path.display()))?;

        let now = unix_now();
        self.db.lock().execute(
            "INSERT INTO chunks(hash, size, last_access) VALUES (?, ?, ?)
             ON CONFLICT(hash) DO UPDATE SET last_access = excluded.last_access",
            params![hash, bytes.len() as i64, now],
        )?;
        Ok(())
    }

    pub fn get(&self, hash: &[u8]) -> Result<Option<Vec<u8>>> {
        if hash.len() != 32 {
            return Ok(None);
        }
        let path = self.chunk_path(hash);
        let bytes = match std::fs::read(&path) {
            Ok(b) => b,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                // Index may have a stale row (e.g. external cleanup); clear it.
                self.db
                    .lock()
                    .execute("DELETE FROM chunks WHERE hash = ?", params![hash])?;
                return Ok(None);
            }
            Err(e) => return Err(e.into()),
        };

        let actual = blake3::hash(&bytes);
        if actual.as_bytes() != hash {
            // Cache poisoning: drop the chunk + index row, audit, force refetch.
            let _ = std::fs::remove_file(&path);
            self.db
                .lock()
                .execute("DELETE FROM chunks WHERE hash = ?", params![hash])?;
            if let Some(audit) = &self.audit {
                let mut event = crate::audit::AuditEvent::simple(
                    "cache_corrupt",
                    &hex_encode(hash),
                    false,
                    crate::audit::AuditIdentity::default(),
                );
                event.size = Some(bytes.len() as u64);
                audit.record(event);
            }
            return Ok(None);
        }

        self.db.lock().execute(
            "UPDATE chunks SET last_access = ? WHERE hash = ?",
            params![unix_now(), hash],
        )?;
        Ok(Some(bytes))
    }

    #[cfg(test)]
    pub fn chunk_path_for_test(&self, hash: &[u8]) -> PathBuf {
        self.chunk_path(hash)
    }

    pub fn total_bytes(&self) -> Result<u64> {
        let db = self.db.lock();
        let n: i64 = db.query_row("SELECT COALESCE(SUM(size), 0) FROM chunks", [], |row| {
            row.get(0)
        })?;
        Ok(n as u64)
    }

    pub fn max_bytes(&self) -> u64 {
        self.max_bytes
    }

    pub fn stats(&self) -> Result<CacheStats> {
        let db = self.db.lock();
        let (count, total): (i64, i64) = db.query_row(
            "SELECT COUNT(*), COALESCE(SUM(size), 0) FROM chunks",
            [],
            |r| Ok((r.get(0)?, r.get(1)?)),
        )?;
        Ok(CacheStats {
            count: count as u64,
            total_bytes: total as u64,
            max_bytes: self.max_bytes,
        })
    }

    /// Evict least-recently-used chunks until `total_bytes <= max_bytes`.
    /// Returns the number of evictions. Delegates to `prune_to_target`.
    pub fn prune(&self) -> Result<u64> {
        self.prune_to_target(self.max_bytes, "high_water")
    }

    /// Low-water mark: evict down to this size to avoid churn at the boundary.
    /// Currently fixed at 90% of `max_bytes`. If churn becomes a concern,
    /// promote this to a config field.
    pub fn low_water_bytes(&self) -> u64 {
        (self.max_bytes / 10) * 9
    }

    /// LRU-evicts until `total_bytes <= low_water_bytes()`. Audited as
    /// `cache_evicted` with reason="low_water".
    pub fn prune_to_low_water(&self) -> Result<u64> {
        self.prune_to_target(self.low_water_bytes(), "low_water")
    }

    /// Compute the eviction plan that `prune_to_low_water` *would* produce,
    /// without removing any files or mutating the index. Useful for
    /// reporting / debugging cache pressure.
    pub fn prune_dry_run(&self) -> Result<DryRunPlan> {
        let target = self.low_water_bytes();
        let mut total = self.total_bytes()?;
        let mut would_evict: Vec<(Vec<u8>, u64)> = Vec::new();
        let mut bytes_freed: u64 = 0;
        if total <= target {
            return Ok(DryRunPlan {
                would_evict,
                bytes_freed,
            });
        }
        let db = self.db.lock();
        let mut stmt =
            db.prepare("SELECT hash, size FROM chunks ORDER BY last_access ASC, hash ASC")?;
        let rows = stmt.query_map([], |r| {
            let h: Vec<u8> = r.get(0)?;
            let size: i64 = r.get(1)?;
            Ok((h, size as u64))
        })?;
        for row in rows {
            let (h, size) = row?;
            if total <= target {
                break;
            }
            bytes_freed = bytes_freed.saturating_add(size);
            total = total.saturating_sub(size);
            would_evict.push((h, size));
        }
        Ok(DryRunPlan {
            would_evict,
            bytes_freed,
        })
    }

    fn prune_to_target(&self, target: u64, reason: &str) -> Result<u64> {
        let mut total = self.total_bytes()?;
        let mut evicted = 0u64;
        let mut bytes_freed = 0u64;
        while total > target {
            let row: Option<(Vec<u8>, i64)> = self
                .db
                .lock()
                .query_row(
                    "SELECT hash, size FROM chunks ORDER BY last_access ASC, hash ASC LIMIT 1",
                    [],
                    |r| Ok((r.get(0)?, r.get(1)?)),
                )
                .optional()?;
            let Some((hash, size)) = row else { break };
            let path = self.chunk_path(&hash);
            let _ = std::fs::remove_file(&path);
            self.db
                .lock()
                .execute("DELETE FROM chunks WHERE hash = ?", params![hash])?;
            total = total.saturating_sub(size as u64);
            bytes_freed = bytes_freed.saturating_add(size as u64);
            evicted += 1;
        }
        if let Some(audit) = self.audit.as_ref().filter(|_| evicted > 0) {
            self.record_eviction(audit, evicted, bytes_freed, reason);
        }
        Ok(evicted)
    }

    fn record_eviction(
        &self,
        audit: &crate::audit::AuditLog,
        count: u64,
        bytes_freed: u64,
        reason: &str,
    ) {
        let mut event = crate::audit::AuditEvent::simple(
            "cache_evicted",
            "",
            true,
            crate::audit::AuditIdentity::default(),
        );
        event.size = Some(bytes_freed);
        event.chunks_reused = Some(count as u32);
        event.reason = Some(reason.to_string());
        audit.record(event);
    }
}

pub(crate) fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push_str(&format!("{:02x}", b));
    }
    out
}

fn unix_now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn open_creates_root_and_db() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024 * 1024, None).unwrap();
        assert!(cache.root().join("chunks").is_dir());
        assert!(cache.root().join("index.sqlite").is_file());
    }

    #[test]
    fn put_then_get_returns_bytes() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024 * 1024, None).unwrap();
        let bytes = b"hello world".to_vec();
        let hash = blake3::hash(&bytes);
        cache.put(hash.as_bytes(), &bytes).unwrap();
        let got = cache.get(hash.as_bytes()).unwrap().expect("hit");
        assert_eq!(got, bytes);
    }

    #[test]
    fn put_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024 * 1024, None).unwrap();
        let bytes = b"abc".to_vec();
        let hash = blake3::hash(&bytes);
        cache.put(hash.as_bytes(), &bytes).unwrap();
        cache.put(hash.as_bytes(), &bytes).unwrap();
        assert_eq!(cache.total_bytes().unwrap(), bytes.len() as u64);
    }

    #[test]
    fn get_miss_returns_none() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024 * 1024, None).unwrap();
        let absent = blake3::hash(b"nope");
        assert!(cache.get(absent.as_bytes()).unwrap().is_none());
    }

    #[test]
    fn stats_returns_total_and_count() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024, None).unwrap();
        let a = b"aaa".to_vec();
        let b = b"bbbb".to_vec();
        cache.put(blake3::hash(&a).as_bytes(), &a).unwrap();
        cache.put(blake3::hash(&b).as_bytes(), &b).unwrap();
        let s = cache.stats().unwrap();
        assert_eq!(s.count, 2);
        assert_eq!(s.total_bytes, 7);
        assert_eq!(s.max_bytes, 1024);
    }

    #[test]
    fn prune_evicts_lru_until_under_max() {
        let dir = tempfile::tempdir().unwrap();
        // Cap = 5 bytes; we'll insert three 3-byte chunks → 9 bytes total.
        let cache = ChunkCache::open(dir.path().to_path_buf(), 5, None).unwrap();
        let a = b"aaa".to_vec();
        let b = b"bbb".to_vec();
        let c = b"ccc".to_vec();
        let ha = blake3::hash(&a);
        let hb = blake3::hash(&b);
        let hc = blake3::hash(&c);

        cache.put(ha.as_bytes(), &a).unwrap();
        std::thread::sleep(std::time::Duration::from_millis(1100));
        cache.put(hb.as_bytes(), &b).unwrap();
        std::thread::sleep(std::time::Duration::from_millis(1100));
        cache.put(hc.as_bytes(), &c).unwrap();

        let evicted = cache.prune().unwrap();
        assert!(evicted >= 1, "expected at least one eviction");
        assert!(cache.total_bytes().unwrap() <= 5);
        // Most recently used (c) must survive.
        assert!(cache.get(hc.as_bytes()).unwrap().is_some());
        // Oldest (a) must be evicted.
        assert!(cache.get(ha.as_bytes()).unwrap().is_none());
    }

    #[test]
    fn prune_to_low_water_evicts_oldest_until_under_low_water() {
        let dir = tempfile::tempdir().unwrap();
        // 1024 max, low_water = 90% = 921 bytes.
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024, None).unwrap();
        // Three 400-byte chunks: total 1200 > max.
        let payloads = ["a", "b", "c"].map(|s| s.repeat(400).into_bytes());
        let mut hashes = Vec::new();
        for p in &payloads {
            let h = blake3::hash(p);
            cache.put(h.as_bytes(), p).unwrap();
            // `last_access` is stored at second granularity (unix_now()),
            // so sleep > 1s to give each insert a distinct timestamp.
            std::thread::sleep(std::time::Duration::from_millis(1100));
            hashes.push(*h.as_bytes());
        }
        let evicted = cache.prune_to_low_water().unwrap();
        let after = cache.stats().unwrap();
        assert!(
            after.total_bytes <= 921,
            "total {} > low_water 921",
            after.total_bytes
        );
        assert!(evicted >= 1, "expected at least 1 eviction, got {evicted}");
        // The first-inserted chunk (oldest last_access) goes first.
        assert!(
            cache.get(&hashes[0]).unwrap().is_none(),
            "oldest chunk should be evicted first"
        );
    }

    #[test]
    fn prune_to_low_water_noop_when_under_low_water() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 10_000, None).unwrap();
        let bytes = b"small".to_vec();
        let h = blake3::hash(&bytes);
        cache.put(h.as_bytes(), &bytes).unwrap();
        let evicted = cache.prune_to_low_water().unwrap();
        assert_eq!(evicted, 0);
        assert!(cache.get(h.as_bytes()).unwrap().is_some());
    }

    #[test]
    fn prune_dry_run_does_not_modify_state() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024, None).unwrap();
        let payloads = ["x", "y", "z"].map(|s| s.repeat(400).into_bytes());
        for p in &payloads {
            let h = blake3::hash(p);
            cache.put(h.as_bytes(), p).unwrap();
        }
        let before = cache.stats().unwrap();
        let plan = cache.prune_dry_run().unwrap();
        let after = cache.stats().unwrap();
        assert_eq!(before.count, after.count, "dry-run mutated row count");
        assert_eq!(
            before.total_bytes, after.total_bytes,
            "dry-run mutated bytes"
        );
        assert!(
            !plan.would_evict.is_empty(),
            "dry-run reported no evictions for over-quota cache"
        );
        let total_planned: u64 = plan.would_evict.iter().map(|(_, n)| *n).sum();
        assert_eq!(total_planned, plan.bytes_freed);
    }

    #[test]
    fn prune_to_low_water_emits_cache_evicted_audit() {
        let dir = tempfile::tempdir().unwrap();
        let audit_path = dir.path().join("audit.log");
        let audit = crate::audit::AuditLog::new(audit_path.clone()).unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024, Some(audit.clone())).unwrap();

        for s in &["a", "b", "c"] {
            let bytes = s.repeat(400).into_bytes();
            let h = blake3::hash(&bytes);
            cache.put(h.as_bytes(), &bytes).unwrap();
        }
        let evicted = cache.prune_to_low_water().unwrap();
        assert!(evicted >= 1);

        audit.flush().unwrap();
        let log = std::fs::read_to_string(&audit_path).unwrap();
        assert!(
            log.lines()
                .any(|l| l.contains(r#""event":"cache_evicted""#)),
            "no cache_evicted line in audit: {log}",
        );
    }

    #[test]
    fn get_corrupted_chunk_is_deleted_and_returns_none() {
        let dir = tempfile::tempdir().unwrap();
        let cache = ChunkCache::open(dir.path().to_path_buf(), 1024 * 1024, None).unwrap();
        let bytes = b"good".to_vec();
        let hash = blake3::hash(&bytes);
        cache.put(hash.as_bytes(), &bytes).unwrap();

        // Tamper with the on-disk chunk.
        let path = cache.chunk_path_for_test(hash.as_bytes());
        std::fs::write(&path, b"BAD!").unwrap();

        assert!(
            cache.get(hash.as_bytes()).unwrap().is_none(),
            "corrupt chunk reported as hit"
        );
        assert!(!path.exists(), "corrupt chunk not deleted");
        assert_eq!(cache.total_bytes().unwrap(), 0);
    }
}
