// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (token_hash, purpose, user_id, tenant_id, expires_at, allocation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token_hash, purpose, user_id, tenant_id, allocation_id, expires_at, revoked_at, created_at
`

type CreateAccessTokenParams struct {
	TokenHash    string
	Purpose      string
	UserID       pgtype.UUID
	TenantID     string
	ExpiresAt    pgtype.Timestamptz
	AllocationID pgtype.UUID
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.TokenHash,
		arg.Purpose,
		arg.UserID,
		arg.TenantID,
		arg.ExpiresAt,
		arg.AllocationID,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Purpose,
		&i.UserID,
		&i.TenantID,
		&i.AllocationID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT
    t.id,
    t.token_hash,
    t.purpose,
    t.user_id,
    t.tenant_id,
    t.expires_at,
    t.revoked_at,
    t.created_at,
    t.allocation_id,
    u.suspended_at AS user_suspended_at,
    ten.suspended_at AS tenant_suspended_at
FROM access_tokens t
JOIN users   u   ON u.id = t.user_id
JOIN tenants ten ON ten.id = t.tenant_id
WHERE t.token_hash = $1
`

type GetAccessTokenByHashRow struct {
	ID                pgtype.UUID
	TokenHash         string
	Purpose           string
	UserID            pgtype.UUID
	TenantID          string
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	AllocationID      pgtype.UUID
	UserSuspendedAt   pgtype.Timestamptz
	TenantSuspendedAt pgtype.Timestamptz
}

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (GetAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i GetAccessTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Purpose,
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.AllocationID,
		&i.UserSuspendedAt,
		&i.TenantSuspendedAt,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeAccessToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, tokenHash)
	return err
}
