// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_enrollments.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentEnrollment = `-- name: CreateAgentEnrollment :one
INSERT INTO agent_enrollments (user_id, cert_serial, cert_not_after)
VALUES ($1, $2, $3)
RETURNING id, user_id, cert_serial, cert_not_after, enrolled_at
`

type CreateAgentEnrollmentParams struct {
	UserID       pgtype.UUID
	CertSerial   string
	CertNotAfter pgtype.Timestamptz
}

func (q *Queries) CreateAgentEnrollment(ctx context.Context, arg CreateAgentEnrollmentParams) (AgentEnrollment, error) {
	row := q.db.QueryRow(ctx, createAgentEnrollment, arg.UserID, arg.CertSerial, arg.CertNotAfter)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CertSerial,
		&i.CertNotAfter,
		&i.EnrolledAt,
	)
	return i, err
}

const getActiveEnrollmentByFingerprint = `-- name: GetActiveEnrollmentByFingerprint :one
SELECT id, user_id, cert_serial, cert_not_after, enrolled_at FROM agent_enrollments
WHERE lower(cert_serial) = lower($1) AND cert_not_after > now()
`

func (q *Queries) GetActiveEnrollmentByFingerprint(ctx context.Context, lower string) (AgentEnrollment, error) {
	row := q.db.QueryRow(ctx, getActiveEnrollmentByFingerprint, lower)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CertSerial,
		&i.CertNotAfter,
		&i.EnrolledAt,
	)
	return i, err
}

const listActiveEnrollmentsForUser = `-- name: ListActiveEnrollmentsForUser :many
SELECT id, user_id, cert_serial, cert_not_after, enrolled_at FROM agent_enrollments
WHERE user_id = $1 AND cert_not_after > now()
ORDER BY enrolled_at DESC
`

func (q *Queries) ListActiveEnrollmentsForUser(ctx context.Context, userID pgtype.UUID) ([]AgentEnrollment, error) {
	rows, err := q.db.Query(ctx, listActiveEnrollmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEnrollment{}
	for rows.Next() {
		var i AgentEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CertSerial,
			&i.CertNotAfter,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
