// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cert_revocations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCertRevocation = `-- name: AddCertRevocation :exec
INSERT INTO cert_revocations (cert_serial, tenant_id, expires_at, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cert_serial) DO NOTHING
`

type AddCertRevocationParams struct {
	CertSerial string
	TenantID   string
	ExpiresAt  pgtype.Timestamptz
	Reason     string
}

// Record a revoked cert serial (issue #5). Idempotent: a serial already on the
// deny-list is left untouched (the first revocation's reason/expiry win).
func (q *Queries) AddCertRevocation(ctx context.Context, arg AddCertRevocationParams) error {
	_, err := q.db.Exec(ctx, addCertRevocation,
		arg.CertSerial,
		arg.TenantID,
		arg.ExpiresAt,
		arg.Reason,
	)
	return err
}

const deleteExpiredCertRevocations = `-- name: DeleteExpiredCertRevocations :exec
DELETE FROM cert_revocations WHERE expires_at <= now()
`

// Housekeeping: drop rows whose certs have already expired.
func (q *Queries) DeleteExpiredCertRevocations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCertRevocations)
	return err
}

const listActiveCertRevocations = `-- name: ListActiveCertRevocations :many
SELECT cert_serial, expires_at
FROM cert_revocations
WHERE expires_at > now()
ORDER BY expires_at
`

type ListActiveCertRevocationsRow struct {
	CertSerial string
	ExpiresAt  pgtype.Timestamptz
}

// The deny-list the reconcile loop pushes to data-plane servers: serials whose
// certs have not yet expired (an expired cert fails verification anyway).
func (q *Queries) ListActiveCertRevocations(ctx context.Context) ([]ListActiveCertRevocationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCertRevocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCertRevocationsRow{}
	for rows.Next() {
		var i ListActiveCertRevocationsRow
		if err := rows.Scan(&i.CertSerial, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServerOpsAddrs = `-- name: ListActiveServerOpsAddrs :many
SELECT DISTINCT sp.ops_addr
FROM server_vms sv
JOIN server_pool sp ON sp.data_addr = sv.data_addr
`

// Distinct orlop-server ops addresses that currently host at least one placed
// tenant — the push targets for the deny-list reconcile.
func (q *Queries) ListActiveServerOpsAddrs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveServerOpsAddrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ops_addr string
		if err := rows.Scan(&ops_addr); err != nil {
			return nil, err
		}
		items = append(items, ops_addr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
