// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_authorizations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDeviceAuthorization = `-- name: ApproveDeviceAuthorization :one
UPDATE device_authorizations
SET status = 'approved', approved_at = now(), tenant_id = $2, user_id = $3, allocation_id = $4
WHERE id = $1 AND status = 'pending'
RETURNING id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at
`

type ApproveDeviceAuthorizationParams struct {
	ID           pgtype.UUID
	TenantID     pgtype.Text
	UserID       pgtype.UUID
	AllocationID pgtype.UUID
}

func (q *Queries) ApproveDeviceAuthorization(ctx context.Context, arg ApproveDeviceAuthorizationParams) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, approveDeviceAuthorization,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.AllocationID,
	)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDeviceAuthorization = `-- name: CreateDeviceAuthorization :one
INSERT INTO device_authorizations (device_code_hash, user_code_hash, status, expires_at)
VALUES ($1, $2, 'pending', $3)
RETURNING id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at
`

type CreateDeviceAuthorizationParams struct {
	DeviceCodeHash string
	UserCodeHash   string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateDeviceAuthorization(ctx context.Context, arg CreateDeviceAuthorizationParams) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, createDeviceAuthorization, arg.DeviceCodeHash, arg.UserCodeHash, arg.ExpiresAt)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const denyDeviceAuthorization = `-- name: DenyDeviceAuthorization :one
UPDATE device_authorizations
SET status = 'denied', tenant_id = $2, user_id = $3
WHERE id = $1 AND status = 'pending'
RETURNING id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at
`

type DenyDeviceAuthorizationParams struct {
	ID       pgtype.UUID
	TenantID pgtype.Text
	UserID   pgtype.UUID
}

func (q *Queries) DenyDeviceAuthorization(ctx context.Context, arg DenyDeviceAuthorizationParams) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, denyDeviceAuthorization, arg.ID, arg.TenantID, arg.UserID)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceAuthorizationByDeviceCodeHash = `-- name: GetDeviceAuthorizationByDeviceCodeHash :one
SELECT id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at FROM device_authorizations WHERE device_code_hash = $1
`

func (q *Queries) GetDeviceAuthorizationByDeviceCodeHash(ctx context.Context, deviceCodeHash string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getDeviceAuthorizationByDeviceCodeHash, deviceCodeHash)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceAuthorizationByUserCodeHash = `-- name: GetDeviceAuthorizationByUserCodeHash :one
SELECT id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at FROM device_authorizations WHERE user_code_hash = $1
`

func (q *Queries) GetDeviceAuthorizationByUserCodeHash(ctx context.Context, userCodeHash string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getDeviceAuthorizationByUserCodeHash, userCodeHash)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeviceAuthorizationByUserCodeHashForUpdate = `-- name: GetPendingDeviceAuthorizationByUserCodeHashForUpdate :one
SELECT id, device_code_hash, user_code_hash, tenant_id, user_id, allocation_id, status, expires_at, approved_at, last_polled_at, created_at FROM device_authorizations
WHERE user_code_hash = $1
FOR UPDATE
`

func (q *Queries) GetPendingDeviceAuthorizationByUserCodeHashForUpdate(ctx context.Context, userCodeHash string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getPendingDeviceAuthorizationByUserCodeHashForUpdate, userCodeHash)
	var i DeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.TenantID,
		&i.UserID,
		&i.AllocationID,
		&i.Status,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.CreatedAt,
	)
	return i, err
}

const markDeviceAuthorizationExchanged = `-- name: MarkDeviceAuthorizationExchanged :exec
UPDATE device_authorizations SET status = 'exchanged' WHERE id = $1
`

func (q *Queries) MarkDeviceAuthorizationExchanged(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeviceAuthorizationExchanged, id)
	return err
}

const markDeviceAuthorizationExpired = `-- name: MarkDeviceAuthorizationExpired :exec
UPDATE device_authorizations SET status = 'expired' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkDeviceAuthorizationExpired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeviceAuthorizationExpired, id)
	return err
}

const touchDeviceAuthorizationPoll = `-- name: TouchDeviceAuthorizationPoll :exec
UPDATE device_authorizations
SET last_polled_at = $2
WHERE id = $1
`

type TouchDeviceAuthorizationPollParams struct {
	ID           pgtype.UUID
	LastPolledAt pgtype.Timestamptz
}

func (q *Queries) TouchDeviceAuthorizationPoll(ctx context.Context, arg TouchDeviceAuthorizationPollParams) error {
	_, err := q.db.Exec(ctx, touchDeviceAuthorizationPoll, arg.ID, arg.LastPolledAt)
	return err
}
