// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_otps.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailOTP = `-- name: ConsumeEmailOTP :one
UPDATE email_otps
SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
RETURNING id, email, code_hash, expires_at, consumed_at, created_at, attempts
`

type ConsumeEmailOTPParams struct {
	ID         pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeEmailOTP(ctx context.Context, arg ConsumeEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, consumeEmailOTP, arg.ID, arg.ConsumedAt)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const createEmailOTP = `-- name: CreateEmailOTP :one
INSERT INTO email_otps (email, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, code_hash, expires_at, consumed_at, created_at, attempts
`

type CreateEmailOTPParams struct {
	Email     string
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, createEmailOTP, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const getLatestEmailOTPForUpdate = `-- name: GetLatestEmailOTPForUpdate :one
SELECT id, email, code_hash, expires_at, consumed_at, created_at, attempts FROM email_otps
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLatestEmailOTPForUpdate(ctx context.Context, email string) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, getLatestEmailOTPForUpdate, email)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const incrementEmailOTPAttempts = `-- name: IncrementEmailOTPAttempts :one
UPDATE email_otps
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementEmailOTPAttempts(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementEmailOTPAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
