// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID           pgtype.UUID
	TokenHash    string
	Purpose      string
	UserID       pgtype.UUID
	TenantID     string
	AllocationID pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
}

type AgentEnrollment struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CertSerial   string
	CertNotAfter pgtype.Timestamptz
	EnrolledAt   pgtype.Timestamptz
}

type AnonymousSession struct {
	SessionID    string
	AllocationID pgtype.UUID
	DeviceID     string
	CertSerial   string
	SpawnerUrl   string
	IpAddress    netip.Addr
	UserAgent    string
	CreatedAt    pgtype.Timestamptz
	ClaimedAt    pgtype.Timestamptz
	ClaimedBy    pgtype.UUID
}

type ApiToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	TokenHash  string
	Prefix     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type CertRevocation struct {
	CertSerial string
	TenantID   string
	ExpiresAt  pgtype.Timestamptz
	Reason     string
	RevokedAt  pgtype.Timestamptz
}

type DeviceAuthorization struct {
	ID             pgtype.UUID
	DeviceCodeHash string
	UserCodeHash   string
	TenantID       pgtype.Text
	UserID         pgtype.UUID
	AllocationID   pgtype.UUID
	Status         string
	ExpiresAt      pgtype.Timestamptz
	ApprovedAt     pgtype.Timestamptz
	LastPolledAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type DgCaSecret struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type DiskAllocation struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	SizeBytes      int64
	CreatedAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	BoundAgentID   pgtype.UUID
	BoundAt        pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	AgentID        pgtype.Text
	PurgedAt       pgtype.Timestamptz
	TenantID       pgtype.Text
}

type RefreshToken struct {
	ID           pgtype.UUID
	TokenHash    string
	FamilyID     pgtype.UUID
	UserID       pgtype.UUID
	TenantID     string
	AllocationID pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RotatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type ServerPool struct {
	ID         pgtype.UUID
	DataAddr   string
	OpsAddr    string
	TotalBytes int64
	FreeBytes  int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ServerVm struct {
	ID            pgtype.UUID
	TenantID      string
	DataAddr      string
	ProvisionedAt pgtype.Timestamptz
	Status        string
	CreatedAt     pgtype.Timestamptz
}

type Tenant struct {
	ID          string
	Name        string
	SuspendedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	TenantID    string
	Role        string
	SuspendedAt pgtype.Timestamptz
	QuotaBytes  int64
	CreatedAt   pgtype.Timestamptz
}
