// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, family_id, user_id, tenant_id, expires_at, allocation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token_hash, family_id, user_id, tenant_id, allocation_id, expires_at, revoked_at, rotated_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash    string
	FamilyID     pgtype.UUID
	UserID       pgtype.UUID
	TenantID     string
	ExpiresAt    pgtype.Timestamptz
	AllocationID pgtype.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.FamilyID,
		arg.UserID,
		arg.TenantID,
		arg.ExpiresAt,
		arg.AllocationID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserID,
		&i.TenantID,
		&i.AllocationID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
    t.id,
    t.token_hash,
    t.family_id,
    t.user_id,
    t.tenant_id,
    t.expires_at,
    t.revoked_at,
    t.rotated_at,
    t.created_at,
    t.allocation_id,
    u.suspended_at AS user_suspended_at,
    ten.suspended_at AS tenant_suspended_at
FROM refresh_tokens t
JOIN users   u   ON u.id = t.user_id
JOIN tenants ten ON ten.id = t.tenant_id
WHERE t.token_hash = $1
FOR UPDATE
`

type GetRefreshTokenByHashRow struct {
	ID                pgtype.UUID
	TokenHash         string
	FamilyID          pgtype.UUID
	UserID            pgtype.UUID
	TenantID          string
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	RotatedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	AllocationID      pgtype.UUID
	UserSuspendedAt   pgtype.Timestamptz
	TenantSuspendedAt pgtype.Timestamptz
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.FamilyID,
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.AllocationID,
		&i.UserSuspendedAt,
		&i.TenantSuspendedAt,
	)
	return i, err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens SET rotated_at = now() WHERE id = $1 AND rotated_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
