// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_vms.sql

package sqlcdb

import (
	"context"
)

const createServerVM = `-- name: CreateServerVM :one
INSERT INTO server_vms (tenant_id, data_addr, status)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, data_addr, provisioned_at, status, created_at
`

type CreateServerVMParams struct {
	TenantID string
	DataAddr string
	Status   string
}

func (q *Queries) CreateServerVM(ctx context.Context, arg CreateServerVMParams) (ServerVm, error) {
	row := q.db.QueryRow(ctx, createServerVM, arg.TenantID, arg.DataAddr, arg.Status)
	var i ServerVm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DataAddr,
		&i.ProvisionedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServerVM = `-- name: DeleteServerVM :execrows
DELETE FROM server_vms WHERE tenant_id = $1
`

// Remove a tenant's placement after its data-plane tenant was unregistered
// (last-allocation purge). The next enroll for this tenant re-Reserves a
// placement from the pool.
func (q *Queries) DeleteServerVM(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerVM, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServerVMByTenant = `-- name: GetServerVMByTenant :one
SELECT id, tenant_id, data_addr, provisioned_at, status, created_at FROM server_vms WHERE tenant_id = $1
`

func (q *Queries) GetServerVMByTenant(ctx context.Context, tenantID string) (ServerVm, error) {
	row := q.db.QueryRow(ctx, getServerVMByTenant, tenantID)
	var i ServerVm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DataAddr,
		&i.ProvisionedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markServerVMProvisioned = `-- name: MarkServerVMProvisioned :one
UPDATE server_vms
SET provisioned_at = now(), status = $2
WHERE tenant_id = $1
RETURNING id, tenant_id, data_addr, provisioned_at, status, created_at
`

type MarkServerVMProvisionedParams struct {
	TenantID string
	Status   string
}

func (q *Queries) MarkServerVMProvisioned(ctx context.Context, arg MarkServerVMProvisionedParams) (ServerVm, error) {
	row := q.db.QueryRow(ctx, markServerVMProvisioned, arg.TenantID, arg.Status)
	var i ServerVm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DataAddr,
		&i.ProvisionedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
